### PR TITLE
feat: add optional geoData property as alternative to geofile

### PR DESCRIPTION
**Pull request by dpraul**
Hi again! 

We need to use `d3-geomap` in an environment where `fetch` is not available, and we already have the `TopoJSON` contents loaded on the page, so I've added the `geoData` key as an alternative to `geofile`.

You can pass the `TopoJSON` contents in directly to the `geoData` property. In doing so, the `geofile` property is ignored, and `fetch` becomes an optional dependency. No other functionality should be affected.

I also added some inline docs for clarity :)

### CODE REVIEW

**Comment by yaph** [comment]
Thanks for adding this useful feature.

**Comment by dpraul** [comment]
thanks for merging this so quickly! do you intend to do a release anytime soon?

**Comment by yaph** [comment]
Yes, not sure yet if this week or beginning of next week.

**Comment by yaph** [comment]
New release is out.

**Comment by dpraul** [comment]
Thank you!

**Pull request merged**
